"""
报告渲染器
将 Markdown 格式的审计报告转换为 PDF 文件。

使用 fpdf2 进行渲染 (轻量级, 无 GTK 依赖, 适合 Windows 环境)。
支持中文字符渲染。
"""

import os
import re
import sys
from pathlib import Path
from datetime import datetime
from typing import Optional

# 添加项目根目录到 sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from config.settings import REPORTS_DIR


class ReportRenderer:
    """Markdown → PDF 报告渲染器"""

    # 中文字体路径 (使用系统自带的 SimSun 或 Microsoft YaHei)
    CN_FONT_PATHS = [
        "C:/Windows/Fonts/msyh.ttc",      # 微软雅黑
        "C:/Windows/Fonts/simsun.ttc",     # 宋体
        "C:/Windows/Fonts/simhei.ttf",     # 黑体
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",  # Linux fallback
    ]

    def __init__(self):
        self._font_path: Optional[str] = None
        self._find_font()

    def _find_font(self) -> None:
        """查找可用的中文字体"""
        for path in self.CN_FONT_PATHS:
            if os.path.exists(path):
                self._font_path = path
                print(f"[ReportRenderer] 使用字体: {path}")
                return
        print("[ReportRenderer] 警告: 未找到中文字体, PDF 可能无法正确显示中文。")

    def render_to_pdf(self, markdown_content: str, output_filename: Optional[str] = None) -> str:
        """
        将 Markdown 内容渲染为 PDF 文件。

        Args:
            markdown_content: Markdown 格式的报告内容
            output_filename: 输出文件名 (不含路径), 默认按时间戳生成

        Returns:
            PDF 文件的绝对路径
        """
        from fpdf import FPDF

        if not output_filename:
            output_filename = f"audit_report_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"

        output_path = REPORTS_DIR / output_filename

        # 创建 PDF
        pdf = FPDF(orientation="P", unit="mm", format="A4")
        pdf.add_page()

        # 添加中文字体
        if self._font_path:
            pdf.add_font("CN", "", self._font_path, uni=True)
            pdf.set_font("CN", size=10)
        else:
            pdf.set_font("Helvetica", size=10)

        # 设置页边距
        pdf.set_left_margin(20)
        pdf.set_right_margin(20)
        pdf.set_auto_page_break(auto=True, margin=20)

        # 逐行解析 Markdown
        lines = markdown_content.split("\n")
        for line in lines:
            line = line.rstrip()

            # 空行
            if not line:
                pdf.ln(3)
                continue

            # 分割线
            if line.strip() == "---":
                pdf.ln(2)
                pdf.cell(0, 5, "-" * 80, new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)
                continue

            # 标题
            if line.startswith("# "):
                pdf.set_font("CN", size=16)
                pdf.ln(3)
                pdf.multi_cell(0, 8, line[2:])
                pdf.ln(2)
                pdf.set_font("CN", size=10)
            elif line.startswith("## "):
                pdf.set_font("CN", size=13)
                pdf.ln(2)
                pdf.multi_cell(0, 6, line[3:])
                pdf.ln(1)
                pdf.set_font("CN", size=10)
            elif line.startswith("### "):
                pdf.set_font("CN", size=11)
                pdf.ln(1)
                pdf.multi_cell(0, 5, line[4:])
                pdf.set_font("CN", size=10)
            else:
                # 表格行 (简单处理)
                if "|" in line and line.strip().startswith("|"):
                    # 清理 markdown 表格格式
                    clean = line.replace("|", "  ").strip()
                    if set(clean) <= set(" -"):
                        continue  # 跳过分隔行
                    pdf.set_font("CN", size=9)
                    pdf.multi_cell(0, 5, clean)
                    pdf.set_font("CN", size=10)
                else:
                    # 普通文本
                    # 清理 markdown 粗体标记
                    clean = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
                    clean = re.sub(r"\*(.+?)\*", r"\1", clean)
                    clean = re.sub(r"`(.+?)`", r"\1", clean)
                    pdf.multi_cell(0, 5, clean)

        # 添加页脚
        pdf.set_y(-15)
        pdf.set_font("CN", size=8)
        pdf.cell(0, 10, f"Generated by Carbon Compliance Agent v1.0 - Page {pdf.page_no()}", align="C")

        # 保存
        pdf.output(str(output_path))
        print(f"[ReportRenderer] PDF 报告已保存: {output_path}")

        return str(output_path)

    def render_to_file(self, markdown_content: str, output_filename: Optional[str] = None) -> str:
        """
        同时保存 Markdown 和 PDF 文件。

        Args:
            markdown_content: Markdown 格式内容
            output_filename: 文件名 (不含扩展名)

        Returns:
            PDF 文件路径
        """
        if output_filename:
            md_path = REPORTS_DIR / f"{output_filename}.md"
            md_path.write_text(markdown_content, encoding="utf-8")
            print(f"[ReportRenderer] Markdown 报告已保存: {md_path}")

        return self.render_to_pdf(markdown_content, output_filename)


# ========================================
# 模块级便捷接口
# ========================================

_renderer_instance: Optional[ReportRenderer] = None


def get_renderer() -> ReportRenderer:
    """获取全局报告渲染器单例"""
    global _renderer_instance
    if _renderer_instance is None:
        _renderer_instance = ReportRenderer()
    return _renderer_instance


def render_report(markdown_content: str, filename: Optional[str] = None) -> str:
    """
    便捷接口: 将 Markdown 报告渲染为 PDF。

    Args:
        markdown_content: Markdown 格式报告
        filename: 输出文件名 (可选)

    Returns:
        PDF 文件路径
    """
    renderer = get_renderer()
    return renderer.render_to_file(markdown_content, filename)


# ========================================
# 主程序: 快速验证
# ========================================

if __name__ == "__main__":
    print("=" * 60)
    print("报告渲染器 - 功能测试")
    print("=" * 60)

    test_md = """# 测试审计报告

## 一、概述

这是一个测试报告, 用于验证 PDF 渲染功能。

### 产品信息

| 项目 | 内容 |
|------|------|
| 产品名称 | 铝合金型材 |
| HS Code | 7604 |
| 重量 | 60 吨 |

## 二、碳排放结果

- Scope 1: 990.0000 tCO2e
- Scope 2: 697.2000 tCO2e
- Scope 3: 17.2200 tCO2e
- **总排放量: 1704.4200 tCO2e**

---

免责声明: 本报告由 AI 系统自动生成。
"""

    pdf_path = render_report(test_md, "test_report")
    print(f"\nPDF 文件路径: {pdf_path}")
    print("\n=== 报告渲染器测试完成 ===")
